spring:
  datasource:
    url: jdbc:h2:mem:prices-db
    username: sgb
    password: sgb9182
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    user: sgb
    password: sgb9182
    locations:
      - classpath:db/migration

